In [4]:
import plotly.offline as py
py.init_notebook_mode(connected=True)
import plotly.graph_objs as go
import pandas as pd
table = pd.read_csv('data-python/mt_bruno_elevation.csv')
data = go.Surface(z=table.values)  # use 2D numpy array format
layout = go.Layout(title='Mt Bruno Elevation',
                   width=400, height=400,    # image size
                   margin=dict(l=65, r=10, b=65, t=90))   # margins around the plot
fig = go.Figure(data=[data], layout=layout)
py.iplot(fig)

<class 'int'>
<class 'float'>
<class 'str'>


In [5]:
print(type(100+'test'))

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [6]:
list = [1, 20, 'vancouver',5]
list.sort()
print(list)

TypeError: '<' not supported between instances of 'str' and 'int'

In [7]:
print(list)

[1, 20, 'vancouver', 5]


In [8]:
list.insert(2, 'surrey')

In [9]:
print(list)

[1, 20, 'surrey', 'vancouver', 5]


In [10]:
range(1:10)

SyntaxError: invalid syntax (<ipython-input-10-61ede8291e8c>, line 1)

In [15]:
word = 'computer'
for i in range(len(word)):
    print(word[len(word)-1-i],end = ''")

SyntaxError: EOL while scanning string literal (<ipython-input-15-d66ba932fe2c>, line 3)

In [19]:
word  = 'computer'
word 

['r', 't', 'p', 'o', 'c', 'm', 'u', 'e']


In [20]:
set([1,2,3,4]) - set([2,5])


{1, 3, 4}

In [21]:
print(table.values)

[[ 0.000000e+00  2.780985e+01  4.961936e+01  8.308067e+01  1.166632e+02
   1.304140e+02  1.507206e+02  2.201871e+02  1.561536e+02  1.486416e+02
   2.037845e+02  2.060386e+02  1.071618e+02  6.836975e+01  4.533590e+01
   4.996142e+01  2.189279e+01  1.702552e+01  1.174317e+01  1.475226e+01
   1.366710e+01  5.677561e+00  3.312340e+00  1.156517e+00 -1.476620e-01]
 [ 1.000000e+00  2.771966e+01  4.855022e+01  6.521374e+01  9.527666e+01
   1.169964e+02  1.339056e+02  1.523412e+02  1.519340e+02  1.601139e+02
   1.795327e+02  1.476184e+02  1.703943e+02  1.218194e+02  5.258537e+01
   3.308871e+01  3.840972e+01  4.424843e+01  6.957860e+01  4.019351e+00
   3.050024e+00  3.039719e+00  2.996142e+00  2.967954e+00  1.999594e+00]
 [ 2.000000e+00  3.042670e+01  3.347752e+01  4.480953e+01  6.247495e+01
   7.743523e+01  1.042153e+02  1.027393e+02  1.370004e+02  1.860706e+02
   2.193173e+02  1.817615e+02  1.209154e+02  1.431835e+02  8.240501e+01
   4.847132e+01  7.471461e+01  6.009090e+01  7.073525e+00  6.0

In [29]:
df = {}
columns = ['user', 'group', 'name', 'id', 'class', 'profile_name', 'config_name']
for c in columns:
        df[c] = []

print(df)
print(type(df))

{'user': [], 'group': [], 'name': [], 'id': [], 'class': [], 'profile_name': [], 'config_name': []}
<class 'dict'>


In [30]:
data = [1:100]
print (data)

SyntaxError: invalid syntax (<ipython-input-30-0ce62b0edccd>, line 1)

In [31]:
colors = ['red','green','white','black', 'pink', 'yellow']
n = 5
sortedColors = [x for x in colors if len(x)< n]
print(sortedColors)

['red', 'pink']


In [33]:
import math
print(math.isqrt(2))

AttributeError: module 'math' has no attribute 'isqrt'

In [34]:
?import

Object `import` not found.


In [36]:
import sys
sys.modules.keys()

et.baxis._linecolor', 'plotly.validators.carpet.baxis._minorgridcolor', 'plotly.validators.carpet.baxis._startlinecolor', 'plotly.validators.layout.template.data._choropleth', 'plotly.graph_objs.layout.template.data._choropleth', 'plotly.graph_objs._choropleth', 'plotly.validators.choropleth', 'plotly.validators.choropleth._colorbar', 'plotly.graph_objs.choropleth', 'plotly.graph_objs.choropleth._colorbar', 'plotly.validators.choropleth.colorbar', 'plotly.validators.choropleth.colorbar._outlinewidth', 'plotly.validators.choropleth.colorbar._ticks', 'plotly.validators.layout.template.data._contourcarpet', 'plotly.graph_objs.layout.template.data._contourcarpet', 'plotly.graph_objs._contourcarpet', 'plotly.validators.contourcarpet', 'plotly.validators.contourcarpet._colorbar', 'plotly.graph_objs.contourcarpet', 'plotly.graph_objs.contourcarpet._colorbar', 'plotly.validators.contourcarpet.colorbar', 'plotly.validators.contourcarpet.colorbar._outlinewidth', 'plotly.validators.contourcarpet.

In [37]:
print(dir())


['In', 'Out', '_', '_20', '_35', '_36', '_VSCODE_InfoImport', '_VSCODE_RowImport', '_VSCODE_VariableImport', '__', '___', '__builtin__', '__builtins__', '__doc__', '__loader__', '__name__', '__package__', '__spec__', '_dh', '_i', '_i1', '_i10', '_i11', '_i12', '_i13', '_i14', '_i15', '_i16', '_i17', '_i18', '_i19', '_i2', '_i20', '_i21', '_i22', '_i23', '_i24', '_i25', '_i26', '_i27', '_i28', '_i29', '_i3', '_i30', '_i31', '_i32', '_i33', '_i34', '_i35', '_i36', '_i37', '_i4', '_i5', '_i6', '_i7', '_i8', '_i9', '_ih', '_ii', '_iii', '_oh', '_rwho_ls', 'a', 'c', 'colors', 'columns', 'data', 'df', 'exit', 'fig', 'get_ipython', 'go', 'i', 'layout', 'list', 'math', 'n', 'os', 'pd', 'py', 'quit', 'sortedColors', 'sys', 'table', 'word']


In [39]:
import sys
for m in sys.modules.values():
  print(m)

nt' from '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/ft2font.cpython-37m-darwin.so'>
<module 'kiwisolver' from '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/kiwisolver.cpython-37m-darwin.so'>
<module 'matplotlib.dates' from '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/dates.py'>
<module 'dateutil.rrule' from '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dateutil/rrule.py'>
<module 'matplotlib.units' from '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/units.py'>
<module 'matplotlib.ticker' from '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/ticker.py'>
<module 'matplotlib.transforms' from '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/transforms.py'>
<module 'matplotlib._path' from '/Library/Frameworks/Pyt

RuntimeError: dictionary changed size during iteration

In [41]:
import math
math.degrees(0.3)

17.188733853924695

In [46]:
import numpy as np

ay = np.random.random(size = (5,5))
print(ay)

[[0.73887335 0.99576745 0.26584875 0.20294121 0.73549908]
 [0.76532825 0.02984166 0.06798988 0.93842731 0.31963978]
 [0.56164381 0.05101401 0.40244992 0.51829131 0.65180827]
 [0.81407788 0.25287906 0.67741126 0.59569469 0.44794267]
 [0.44660641 0.73263912 0.91576305 0.18904401 0.00200715]]


In [47]:
print(ay[0][1])

0.9957674494497538


In [48]:
(10**2+10)/11

10.0

In [50]:
?np.arange
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

Docstring:
arange([start,] stop[, step,], dtype=None)

Return evenly spaced values within a given interval.

Values are generated within the half-open interval ``[start, stop)``
(in other words, the interval including `start` but excluding `stop`).
For integer arguments the function is equivalent to the Python built-in
`range` function, but returns an ndarray rather than a list.

When using a non-integer step, such as 0.1, the results will often not
be consistent.  It is better to use `numpy.linspace` for these cases.

Parameters
----------
start : number, optional
    Start of interval.  The interval includes this value.  The default
    start value is 0.
stop : number
    End of interval.  The interval does not include this value, except
    in some cases where `step` is not an integer and floating point
    round-off affects the length of `out`.
step : number, optional
    Spacing between values.  For any output `out`, this is the distance
    between two adjacent values, ``out[i+1]

In [51]:
import pandas as pd

products = {'Product': ['Tablet','iPhone','Laptop','Monitor'],
            'Price': [250,800,1200,300]
            }

df = pd.DataFrame(products, columns= ['Product', 'Price'])

products_list = df.values.tolist()
print (products_list)

[['Tablet', 250], ['iPhone', 800], ['Laptop', 1200], ['Monitor', 300]]


In [52]:
amaricas = pd.read_csv('data-python/gapminder_gdp_americas.csv')



In [53]:
amaricas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 14 columns):
continent         25 non-null object
country           25 non-null object
gdpPercap_1952    25 non-null float64
gdpPercap_1957    25 non-null float64
gdpPercap_1962    25 non-null float64
gdpPercap_1967    25 non-null float64
gdpPercap_1972    25 non-null float64
gdpPercap_1977    25 non-null float64
gdpPercap_1982    25 non-null float64
gdpPercap_1987    25 non-null float64
gdpPercap_1992    25 non-null float64
gdpPercap_1997    25 non-null float64
gdpPercap_2002    25 non-null float64
gdpPercap_2007    25 non-null float64
dtypes: float64(12), object(2)
memory usage: 2.8+ KB


In [54]:
list = amaricas.values.tolist()
print (list)

[['Americas', 'Argentina', 5911.315053, 6856.856212000001, 7133.166023000001, 8052.953020999999, 9443.038526, 10079.026740000001, 8997.897412, 9139.671389, 9308.41871, 10967.28195, 8797.640716, 12779.379640000001], ['Americas', 'Bolivia', 2677.3263469999997, 2127.686326, 2180.972546, 2586.886053, 2980.331339, 3548.097832, 3156.510452, 2753.6914899999997, 2961.699694, 3326.143191, 3413.26269, 3822.1370840000004], ['Americas', 'Brazil', 2108.944355, 2487.365989, 3336.585802, 3429.864357, 4985.711467, 6660.118654, 7030.835878, 7807.095818000001, 6950.283020999999, 7957.980823999999, 8131.212843000001, 9065.800825], ['Americas', 'Canada', 11367.16112, 12489.95006, 13462.48555, 16076.58803, 18970.57086, 22090.88306, 22898.79214, 26626.515030000002, 26342.88426, 28954.92589, 33328.96507, 36319.235010000004], ['Americas', 'Chile', 3939.9787890000002, 4315.6227229999995, 4519.094331, 5106.654313, 5494.024437, 4756.763836, 5095.665738000001, 5547.063754, 7596.125964, 10118.053179999999, 10778.7

In [55]:
amaricas.shape()

TypeError: 'tuple' object is not callable

In [56]:
print(amaricas)

continent              country  gdpPercap_1952  gdpPercap_1957  \
0   Americas            Argentina     5911.315053     6856.856212   
1   Americas              Bolivia     2677.326347     2127.686326   
2   Americas               Brazil     2108.944355     2487.365989   
3   Americas               Canada    11367.161120    12489.950060   
4   Americas                Chile     3939.978789     4315.622723   
5   Americas             Colombia     2144.115096     2323.805581   
6   Americas           Costa Rica     2627.009471     2990.010802   
7   Americas                 Cuba     5586.538780     6092.174359   
8   Americas   Dominican Republic     1397.717137     1544.402995   
9   Americas              Ecuador     3522.110717     3780.546651   
10  Americas          El Salvador     3048.302900     3421.523218   
11  Americas            Guatemala     2428.237769     2617.155967   
12  Americas                Haiti     1840.366939     1726.887882   
13  Americas             Honduras    

In [61]:
amaricas.sample(frac = 1)

amaricas.head(10)

continent             country  gdpPercap_1952  gdpPercap_1957  \
0  Americas           Argentina     5911.315053     6856.856212   
1  Americas             Bolivia     2677.326347     2127.686326   
2  Americas              Brazil     2108.944355     2487.365989   
3  Americas              Canada    11367.161120    12489.950060   
4  Americas               Chile     3939.978789     4315.622723   
5  Americas            Colombia     2144.115096     2323.805581   
6  Americas          Costa Rica     2627.009471     2990.010802   
7  Americas                Cuba     5586.538780     6092.174359   
8  Americas  Dominican Republic     1397.717137     1544.402995   
9  Americas             Ecuador     3522.110717     3780.546651   

   gdpPercap_1962  gdpPercap_1967  gdpPercap_1972  gdpPercap_1977  \
0     7133.166023     8052.953021     9443.038526    10079.026740   
1     2180.972546     2586.886053     2980.331339     3548.097832   
2     3336.585802     3429.864357     4985.711467     6660.118654   
3    13462.485550    16076.588030    18970.570860    22090.883060   
4     4519.094331     5106.654313     5494.024437     4756.763836   
5     2492.351109     2678.729839     3264.660041     3815.807870   
6     3460.937025     4161.727834     5118.146939     5926.876967   
7     5180.755910     5690.268015     5305.445256     6380.494966   
8     1662.137359     1653.723003     2189.874499     2681.988900   
9     4086.114078     4579.074215     5280.994710     6679.623260   

   gdpPercap_1982  gdpPercap_1987  gdpPercap_1992  gdpPercap_1997  \
0     8997.897412     9139.671389     9308.418710    10967.281950   
1     3156.510452     2753.691490     2961.699694     3326.143191   
2     7030.835878     7807.095818     6950.283021     7957.980824   
3    22898.792140    26626.515030    26342.884260    28954.925890   
4     5095.665738     5547.063754     7596.125964    10118.053180   
5     4397.575659     4903.219100     5444.648617     6117.361746   
6     5262.734751     5629.915318     6160.416317     6677.045314   
7     7316.918107     7532.924763     5592.843963     5431.990415   
8     2861.092386     2899.842175     3044.214214     3614.101285   
9     7213.791267     6481.776993     7103.702595     7429.455877   

   gdpPercap_2002  gdpPercap_2007  
0     8797.640716    12779.379640  
1     3413.262690     3822.137084  
2     8131.212843     9065.800825  
3    33328.965070    36319.235010  
4    10778.783850    13171.638850  
5     5755.259962     7006.580419  
6     7723.447195     9645.061420  
7     6340.646683     8948.102923  
8     4563.808154     6025.374752  
9     5773.044512     6873.262326